# Generated by Django 5.0.2 on 2024-02-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_refferalsystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferalsystem',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='refferalsystem',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
