# Generated by Django 5.0.2 on 2024-02-17 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_refferalsystem_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refferalsystem',
            name='refer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refferalsystem',
            name='referal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
