# Generated by Django 5.0.2 on 2024-02-17 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_refferalsystem_refer_alter_refferalsystem_referal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refferalsystem',
            name='referal',
        ),
        migrations.AlterField(
            model_name='refferalsystem',
            name='refer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
